// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_tags.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArticleTag = `-- name: CreateArticleTag :exec
INSERT INTO article_tags (article_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateArticleTagParams struct {
	ArticleID uuid.UUID `json:"article_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) CreateArticleTag(ctx context.Context, arg CreateArticleTagParams) error {
	_, err := q.db.Exec(ctx, createArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const deleteArticleTags = `-- name: DeleteArticleTags :exec
DELETE FROM article_tags WHERE article_id = $1
`

func (q *Queries) DeleteArticleTags(ctx context.Context, articleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticleTags, articleID)
	return err
}

const listArticleTags = `-- name: ListArticleTags :many
SELECT t.id, t.name, t.slug, t.created_at FROM tags t
JOIN article_tags at ON at.tag_id = t.id
WHERE at.article_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListArticleTags(ctx context.Context, articleID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listArticleTags, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesByTag = `-- name: ListArticlesByTag :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content, a.cover_image, a.status, a.view_count, a.published_at, a.created_by, a.category_id, a.created_at, a.updated_at, a.website_id, u.name AS author_name, u.avatar_url AS author_avatar,
       c.name AS category_name, c.slug AS category_slug,
       w.name AS website_name, w.slug AS website_slug
FROM articles a
JOIN article_tags at ON at.article_id = a.id
JOIN users u ON u.id = a.created_by
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN websites w ON w.id = a.website_id
WHERE at.tag_id = $1 AND a.status = 'published'
ORDER BY a.published_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesByTagParams struct {
	TagID  uuid.UUID `json:"tag_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListArticlesByTagRow struct {
	ID           uuid.UUID          `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Excerpt      pgtype.Text        `json:"excerpt"`
	Content      string             `json:"content"`
	CoverImage   pgtype.Text        `json:"cover_image"`
	Status       string             `json:"status"`
	ViewCount    int32              `json:"view_count"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	WebsiteID    pgtype.UUID        `json:"website_id"`
	AuthorName   string             `json:"author_name"`
	AuthorAvatar pgtype.Text        `json:"author_avatar"`
	CategoryName pgtype.Text        `json:"category_name"`
	CategorySlug pgtype.Text        `json:"category_slug"`
	WebsiteName  pgtype.Text        `json:"website_name"`
	WebsiteSlug  pgtype.Text        `json:"website_slug"`
}

func (q *Queries) ListArticlesByTag(ctx context.Context, arg ListArticlesByTagParams) ([]ListArticlesByTagRow, error) {
	rows, err := q.db.Query(ctx, listArticlesByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesByTagRow{}
	for rows.Next() {
		var i ListArticlesByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebsiteID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.CategoryName,
			&i.CategorySlug,
			&i.WebsiteName,
			&i.WebsiteSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
