// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countArticles = `-- name: CountArticles :one
SELECT COUNT(*) FROM articles
WHERE ($1::text = '' OR status = $1)
  AND (CAST($2 AS uuid) IS NULL OR website_id = CAST($2 AS uuid))
`

type CountArticlesParams struct {
	Column1   string      `json:"column_1"`
	WebsiteID pgtype.UUID `json:"website_id"`
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles, arg.Column1, arg.WebsiteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (title, slug, excerpt, content, cover_image, status, published_at, created_by, category_id, website_id,
                      source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, title, slug, excerpt, content, cover_image, status, view_count, published_at, created_by, category_id, created_at, updated_at, website_id, source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license
`

type CreateArticleParams struct {
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.CoverImage,
		arg.Status,
		arg.PublishedAt,
		arg.CreatedBy,
		arg.CategoryID,
		arg.WebsiteID,
		arg.SourceUrl,
		arg.SourceType,
		arg.SourceName,
		arg.SourceHash,
		arg.IsAiGenerated,
		arg.ImageCredit,
		arg.ImageSourceUrl,
		arg.ImageLicense,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT a.id, a.title, a.slug, a.excerpt, a.content, a.cover_image, a.status, a.view_count, a.published_at, a.created_by, a.category_id, a.created_at, a.updated_at, a.website_id, a.source_url, a.source_type, a.source_name, a.source_hash, a.is_ai_generated, a.image_credit, a.image_source_url, a.image_license, u.name AS author_name, u.avatar_url AS author_avatar,
       c.name AS category_name, c.slug AS category_slug,
       w.name AS website_name, w.slug AS website_slug
FROM articles a
JOIN users u ON u.id = a.created_by
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN websites w ON w.id = a.website_id
WHERE a.id = $1
`

type GetArticleByIDRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	ViewCount      int32              `json:"view_count"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
	CategoryName   pgtype.Text        `json:"category_name"`
	CategorySlug   pgtype.Text        `json:"category_slug"`
	WebsiteName    pgtype.Text        `json:"website_name"`
	WebsiteSlug    pgtype.Text        `json:"website_slug"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id uuid.UUID) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.CategoryName,
		&i.CategorySlug,
		&i.WebsiteName,
		&i.WebsiteSlug,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT a.id, a.title, a.slug, a.excerpt, a.content, a.cover_image, a.status, a.view_count, a.published_at, a.created_by, a.category_id, a.created_at, a.updated_at, a.website_id, a.source_url, a.source_type, a.source_name, a.source_hash, a.is_ai_generated, a.image_credit, a.image_source_url, a.image_license, u.name AS author_name, u.avatar_url AS author_avatar,
       c.name AS category_name, c.slug AS category_slug,
       w.name AS website_name, w.slug AS website_slug
FROM articles a
JOIN users u ON u.id = a.created_by
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN websites w ON w.id = a.website_id
WHERE a.slug = $1
`

type GetArticleBySlugRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	ViewCount      int32              `json:"view_count"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
	CategoryName   pgtype.Text        `json:"category_name"`
	CategorySlug   pgtype.Text        `json:"category_slug"`
	WebsiteName    pgtype.Text        `json:"website_name"`
	WebsiteSlug    pgtype.Text        `json:"website_slug"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.CategoryName,
		&i.CategorySlug,
		&i.WebsiteName,
		&i.WebsiteSlug,
	)
	return i, err
}

const getArticleBySourceHash = `-- name: GetArticleBySourceHash :one
SELECT id, title, slug, excerpt, content, cover_image, status, view_count, published_at, created_by, category_id, created_at, updated_at, website_id, source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license FROM articles WHERE source_hash = $1
`

func (q *Queries) GetArticleBySourceHash(ctx context.Context, sourceHash pgtype.Text) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySourceHash, sourceHash)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
	)
	return i, err
}

const getArticleBySourceURL = `-- name: GetArticleBySourceURL :one

SELECT id, title, slug, excerpt, content, cover_image, status, view_count, published_at, created_by, category_id, created_at, updated_at, website_id, source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license FROM articles WHERE source_url = $1
`

// --- Scheduler / dedup ---
func (q *Queries) GetArticleBySourceURL(ctx context.Context, sourceUrl pgtype.Text) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySourceURL, sourceUrl)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
	)
	return i, err
}

const getExistingSourceURLs = `-- name: GetExistingSourceURLs :many
SELECT source_url FROM articles WHERE source_url = ANY($1::text[])
`

func (q *Queries) GetExistingSourceURLs(ctx context.Context, dollar_1 []string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getExistingSourceURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var source_url pgtype.Text
		if err := rows.Scan(&source_url); err != nil {
			return nil, err
		}
		items = append(items, source_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementViewCount = `-- name: IncrementViewCount :one
UPDATE articles
SET view_count = view_count + 1
WHERE id = $1
RETURNING view_count
`

func (q *Queries) IncrementViewCount(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementViewCount, id)
	var view_count int32
	err := row.Scan(&view_count)
	return view_count, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content, a.cover_image, a.status, a.view_count, a.published_at, a.created_by, a.category_id, a.created_at, a.updated_at, a.website_id, a.source_url, a.source_type, a.source_name, a.source_hash, a.is_ai_generated, a.image_credit, a.image_source_url, a.image_license, u.name AS author_name, u.avatar_url AS author_avatar,
       c.name AS category_name, c.slug AS category_slug,
       w.name AS website_name, w.slug AS website_slug
FROM articles a
JOIN users u ON u.id = a.created_by
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN websites w ON w.id = a.website_id
WHERE ($1::text = '' OR a.status = $1)
  AND (CAST($4 AS uuid) IS NULL OR a.category_id = CAST($4 AS uuid))
  AND (CAST($5 AS uuid) IS NULL OR a.website_id = CAST($5 AS uuid))
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListArticlesParams struct {
	Column1    string      `json:"column_1"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID pgtype.UUID `json:"category_id"`
	WebsiteID  pgtype.UUID `json:"website_id"`
}

type ListArticlesRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	ViewCount      int32              `json:"view_count"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
	CategoryName   pgtype.Text        `json:"category_name"`
	CategorySlug   pgtype.Text        `json:"category_slug"`
	WebsiteName    pgtype.Text        `json:"website_name"`
	WebsiteSlug    pgtype.Text        `json:"website_slug"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.WebsiteID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebsiteID,
			&i.SourceUrl,
			&i.SourceType,
			&i.SourceName,
			&i.SourceHash,
			&i.IsAiGenerated,
			&i.ImageCredit,
			&i.ImageSourceUrl,
			&i.ImageLicense,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.CategoryName,
			&i.CategorySlug,
			&i.WebsiteName,
			&i.WebsiteSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content, a.cover_image, a.status, a.view_count, a.published_at, a.created_by, a.category_id, a.created_at, a.updated_at, a.website_id, a.source_url, a.source_type, a.source_name, a.source_hash, a.is_ai_generated, a.image_credit, a.image_source_url, a.image_license, u.name AS author_name, u.avatar_url AS author_avatar,
       c.name AS category_name, c.slug AS category_slug,
       w.name AS website_name, w.slug AS website_slug
FROM articles a
JOIN users u ON u.id = a.created_by
LEFT JOIN categories c ON c.id = a.category_id
LEFT JOIN websites w ON w.id = a.website_id
WHERE a.status = 'published'
  AND a.published_at <= NOW()
  AND (CAST($3 AS uuid) IS NULL OR a.website_id = CAST($3 AS uuid))
ORDER BY a.published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedArticlesParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	WebsiteID pgtype.UUID `json:"website_id"`
}

type ListPublishedArticlesRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	ViewCount      int32              `json:"view_count"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
	CategoryName   pgtype.Text        `json:"category_name"`
	CategorySlug   pgtype.Text        `json:"category_slug"`
	WebsiteName    pgtype.Text        `json:"website_name"`
	WebsiteSlug    pgtype.Text        `json:"website_slug"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles, arg.Limit, arg.Offset, arg.WebsiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesRow{}
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.Content,
			&i.CoverImage,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedBy,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WebsiteID,
			&i.SourceUrl,
			&i.SourceType,
			&i.SourceName,
			&i.SourceHash,
			&i.IsAiGenerated,
			&i.ImageCredit,
			&i.ImageSourceUrl,
			&i.ImageLicense,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.CategoryName,
			&i.CategorySlug,
			&i.WebsiteName,
			&i.WebsiteSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    excerpt = COALESCE($3, excerpt),
    content = COALESCE($4, content),
    cover_image = COALESCE($5, cover_image),
    status = COALESCE($6, status),
    published_at = CASE WHEN $6 = 'published' AND published_at IS NULL THEN NOW() ELSE published_at END,
    category_id = COALESCE($7, category_id),
    website_id = COALESCE($8, website_id),
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, slug, excerpt, content, cover_image, status, view_count, published_at, created_by, category_id, created_at, updated_at, website_id, source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license
`

type UpdateArticleParams struct {
	Title      pgtype.Text `json:"title"`
	Slug       pgtype.Text `json:"slug"`
	Excerpt    pgtype.Text `json:"excerpt"`
	Content    pgtype.Text `json:"content"`
	CoverImage pgtype.Text `json:"cover_image"`
	Status     pgtype.Text `json:"status"`
	CategoryID pgtype.UUID `json:"category_id"`
	WebsiteID  pgtype.UUID `json:"website_id"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.Content,
		arg.CoverImage,
		arg.Status,
		arg.CategoryID,
		arg.WebsiteID,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
	)
	return i, err
}

const updateArticleStatus = `-- name: UpdateArticleStatus :one
UPDATE articles
SET status = $2,
    published_at = CASE WHEN $2 = 'published' THEN COALESCE(published_at, NOW()) ELSE published_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, slug, excerpt, content, cover_image, status, view_count, published_at, created_by, category_id, created_at, updated_at, website_id, source_url, source_type, source_name, source_hash, is_ai_generated, image_credit, image_source_url, image_license
`

type UpdateArticleStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateArticleStatus(ctx context.Context, arg UpdateArticleStatusParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticleStatus, arg.ID, arg.Status)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.Content,
		&i.CoverImage,
		&i.Status,
		&i.ViewCount,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WebsiteID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceName,
		&i.SourceHash,
		&i.IsAiGenerated,
		&i.ImageCredit,
		&i.ImageSourceUrl,
		&i.ImageLicense,
	)
	return i, err
}
