// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countArticleComments = `-- name: CountArticleComments :one
SELECT COUNT(*) FROM comments WHERE article_id = $1
`

func (q *Queries) CountArticleComments(ctx context.Context, articleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countArticleComments, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (article_id, user_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, article_id, user_id, parent_id, content, is_approved, created_at
`

type CreateCommentParams struct {
	ArticleID uuid.UUID   `json:"article_id"`
	UserID    uuid.UUID   `json:"user_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Content   string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ArticleID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.IsApproved,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, article_id, user_id, parent_id, content, is_approved, created_at FROM comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.IsApproved,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleComments = `-- name: ListArticleComments :many
SELECT c.id, c.article_id, c.user_id, c.parent_id, c.content, c.is_approved, c.created_at, u.name AS user_name, u.avatar_url AS user_avatar
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.article_id = $1
  AND ($2::boolean OR c.is_approved = TRUE)
ORDER BY c.created_at ASC
`

type ListArticleCommentsParams struct {
	ArticleID uuid.UUID `json:"article_id"`
	Column2   bool      `json:"column_2"`
}

type ListArticleCommentsRow struct {
	ID         uuid.UUID   `json:"id"`
	ArticleID  uuid.UUID   `json:"article_id"`
	UserID     uuid.UUID   `json:"user_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Content    string      `json:"content"`
	IsApproved bool        `json:"is_approved"`
	CreatedAt  time.Time   `json:"created_at"`
	UserName   string      `json:"user_name"`
	UserAvatar pgtype.Text `json:"user_avatar"`
}

func (q *Queries) ListArticleComments(ctx context.Context, arg ListArticleCommentsParams) ([]ListArticleCommentsRow, error) {
	rows, err := q.db.Query(ctx, listArticleComments, arg.ArticleID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleCommentsRow{}
	for rows.Next() {
		var i ListArticleCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.IsApproved,
			&i.CreatedAt,
			&i.UserName,
			&i.UserAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $1,
    is_approved = COALESCE($2, is_approved)
WHERE id = $3
RETURNING id, article_id, user_id, parent_id, content, is_approved, created_at
`

type UpdateCommentParams struct {
	Content    string      `json:"content"`
	IsApproved pgtype.Bool `json:"is_approved"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Content, arg.IsApproved, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.IsApproved,
		&i.CreatedAt,
	)
	return i, err
}
