// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImage     pgtype.Text        `json:"cover_image"`
	Status         string             `json:"status"`
	ViewCount      int32              `json:"view_count"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	WebsiteID      pgtype.UUID        `json:"website_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SourceType     pgtype.Text        `json:"source_type"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceHash     pgtype.Text        `json:"source_hash"`
	IsAiGenerated  bool               `json:"is_ai_generated"`
	ImageCredit    pgtype.Text        `json:"image_credit"`
	ImageSourceUrl pgtype.Text        `json:"image_source_url"`
	ImageLicense   pgtype.Text        `json:"image_license"`
}

type ArticleTag struct {
	ArticleID uuid.UUID `json:"article_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

type Category struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Comment struct {
	ID         uuid.UUID   `json:"id"`
	ArticleID  uuid.UUID   `json:"article_id"`
	UserID     uuid.UUID   `json:"user_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Content    string      `json:"content"`
	IsApproved bool        `json:"is_approved"`
	CreatedAt  time.Time   `json:"created_at"`
}

type SchedulerRun struct {
	ID              uuid.UUID          `json:"id"`
	WebsiteID       pgtype.UUID        `json:"website_id"`
	Status          string             `json:"status"`
	StartedAt       time.Time          `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	ArticlesCreated int32              `json:"articles_created"`
	ArticlesSkipped int32              `json:"articles_skipped"`
	ArticlesFailed  int32              `json:"articles_failed"`
	Error           pgtype.Text        `json:"error"`
	CreatedAt       time.Time          `json:"created_at"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Role      string      `json:"role"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	IsActive  bool        `json:"is_active"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Website struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Domain      pgtype.Text `json:"domain"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
