// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSchedulerRuns = `-- name: CountSchedulerRuns :one
SELECT COUNT(*) FROM scheduler_runs
`

func (q *Queries) CountSchedulerRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSchedulerRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchedulerRun = `-- name: CreateSchedulerRun :one
INSERT INTO scheduler_runs (website_id)
VALUES ($1)
RETURNING id, website_id, status, started_at, finished_at, articles_created, articles_skipped, articles_failed, error, created_at
`

func (q *Queries) CreateSchedulerRun(ctx context.Context, websiteID pgtype.UUID) (SchedulerRun, error) {
	row := q.db.QueryRow(ctx, createSchedulerRun, websiteID)
	var i SchedulerRun
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ArticlesCreated,
		&i.ArticlesSkipped,
		&i.ArticlesFailed,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const finishSchedulerRun = `-- name: FinishSchedulerRun :one
UPDATE scheduler_runs
SET status           = $2,
    finished_at      = NOW(),
    articles_created = $3,
    articles_skipped = $4,
    articles_failed  = $5,
    error            = $6
WHERE id = $1
RETURNING id, website_id, status, started_at, finished_at, articles_created, articles_skipped, articles_failed, error, created_at
`

type FinishSchedulerRunParams struct {
	ID              uuid.UUID   `json:"id"`
	Status          string      `json:"status"`
	ArticlesCreated int32       `json:"articles_created"`
	ArticlesSkipped int32       `json:"articles_skipped"`
	ArticlesFailed  int32       `json:"articles_failed"`
	Error           pgtype.Text `json:"error"`
}

func (q *Queries) FinishSchedulerRun(ctx context.Context, arg FinishSchedulerRunParams) (SchedulerRun, error) {
	row := q.db.QueryRow(ctx, finishSchedulerRun,
		arg.ID,
		arg.Status,
		arg.ArticlesCreated,
		arg.ArticlesSkipped,
		arg.ArticlesFailed,
		arg.Error,
	)
	var i SchedulerRun
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ArticlesCreated,
		&i.ArticlesSkipped,
		&i.ArticlesFailed,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getSchedulerRunByID = `-- name: GetSchedulerRunByID :one
SELECT id, website_id, status, started_at, finished_at, articles_created, articles_skipped, articles_failed, error, created_at FROM scheduler_runs WHERE id = $1
`

func (q *Queries) GetSchedulerRunByID(ctx context.Context, id uuid.UUID) (SchedulerRun, error) {
	row := q.db.QueryRow(ctx, getSchedulerRunByID, id)
	var i SchedulerRun
	err := row.Scan(
		&i.ID,
		&i.WebsiteID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ArticlesCreated,
		&i.ArticlesSkipped,
		&i.ArticlesFailed,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listSchedulerRuns = `-- name: ListSchedulerRuns :many
SELECT id, website_id, status, started_at, finished_at, articles_created, articles_skipped, articles_failed, error, created_at FROM scheduler_runs
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListSchedulerRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSchedulerRuns(ctx context.Context, arg ListSchedulerRunsParams) ([]SchedulerRun, error) {
	rows, err := q.db.Query(ctx, listSchedulerRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchedulerRun{}
	for rows.Next() {
		var i SchedulerRun
		if err := rows.Scan(
			&i.ID,
			&i.WebsiteID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ArticlesCreated,
			&i.ArticlesSkipped,
			&i.ArticlesFailed,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
