// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: websites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWebsites = `-- name: CountWebsites :one
SELECT COUNT(*) FROM websites
`

func (q *Queries) CountWebsites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWebsites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebsite = `-- name: CreateWebsite :one
INSERT INTO websites (name, slug, domain, description, logo_url, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, domain, description, logo_url, is_active, created_at, updated_at
`

type CreateWebsiteParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Domain      pgtype.Text `json:"domain"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateWebsite(ctx context.Context, arg CreateWebsiteParams) (Website, error) {
	row := q.db.QueryRow(ctx, createWebsite,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Description,
		arg.LogoUrl,
		arg.IsActive,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebsite = `-- name: DeleteWebsite :exec
DELETE FROM websites WHERE id = $1
`

func (q *Queries) DeleteWebsite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebsite, id)
	return err
}

const getWebsiteByDomain = `-- name: GetWebsiteByDomain :one
SELECT id, name, slug, domain, description, logo_url, is_active, created_at, updated_at FROM websites WHERE domain = $1
`

func (q *Queries) GetWebsiteByDomain(ctx context.Context, domain pgtype.Text) (Website, error) {
	row := q.db.QueryRow(ctx, getWebsiteByDomain, domain)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebsiteByID = `-- name: GetWebsiteByID :one
SELECT id, name, slug, domain, description, logo_url, is_active, created_at, updated_at FROM websites WHERE id = $1
`

func (q *Queries) GetWebsiteByID(ctx context.Context, id uuid.UUID) (Website, error) {
	row := q.db.QueryRow(ctx, getWebsiteByID, id)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebsiteBySlug = `-- name: GetWebsiteBySlug :one
SELECT id, name, slug, domain, description, logo_url, is_active, created_at, updated_at FROM websites WHERE slug = $1
`

func (q *Queries) GetWebsiteBySlug(ctx context.Context, slug string) (Website, error) {
	row := q.db.QueryRow(ctx, getWebsiteBySlug, slug)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebsites = `-- name: ListWebsites :many
SELECT id, name, slug, domain, description, logo_url, is_active, created_at, updated_at FROM websites
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListWebsitesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWebsites(ctx context.Context, arg ListWebsitesParams) ([]Website, error) {
	rows, err := q.db.Query(ctx, listWebsites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Website{}
	for rows.Next() {
		var i Website
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Domain,
			&i.Description,
			&i.LogoUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebsite = `-- name: UpdateWebsite :one
UPDATE websites
SET name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    domain = COALESCE($3, domain),
    description = COALESCE($4, description),
    logo_url = COALESCE($5, logo_url),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, slug, domain, description, logo_url, is_active, created_at, updated_at
`

type UpdateWebsiteParams struct {
	Name        pgtype.Text `json:"name"`
	Slug        pgtype.Text `json:"slug"`
	Domain      pgtype.Text `json:"domain"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
	IsActive    pgtype.Bool `json:"is_active"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateWebsite(ctx context.Context, arg UpdateWebsiteParams) (Website, error) {
	row := q.db.QueryRow(ctx, updateWebsite,
		arg.Name,
		arg.Slug,
		arg.Domain,
		arg.Description,
		arg.LogoUrl,
		arg.IsActive,
		arg.ID,
	)
	var i Website
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Domain,
		&i.Description,
		&i.LogoUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
