name: DEployyy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  madang:
    runs-on: ubuntu-latest
    steps:
      - name: CRIT
        run: echo "CRIT"
        shell: bash